workflows:
    android-workflow:
        name: Android Workflow
        max_build_duration: 120
        environment:
            android_signing:
                - rti_keystore_roel
            groups:
                - module_credentials
            vars:
                PACKAGE_NAME: "roel.codemagic_ci_cd"
        scripts:
#        - name: Set up local.properties
#          script: |
#              echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
        - name: Get Flutter packages
          script: |
              flutter packages pub get
        - name: Build APK with Flutter
          script: |
              flutter build apk --release
        artifacts:
            - build/**/outputs/**/*.aab
            - build/**/outputs/**/mapping.txt
            - flutter_drive.log