workflows:
    android-workflow:
        name: Android Workflow
        max_build_duration: 120
        environment:
            android_signing:
                - rti_keystore_roel
            groups:
                - module_credentials
            vars:
                PACKAGE_NAME: "roel.codemagic_ci_cd"
        triggering:
          events: # List the events that trigger builds
            - push
            - pull_request
          branch_patterns: # Include or exclude watched branches
            - pattern: 'main'
              include: true
              source: true
          tag_patterns: # Include or exlude watched tag labels
            - pattern: excluded-tag
              include: false
            - pattern: included-tag
              include: true
          cancel_previous_builds: true
        scripts:
#        - name: Set up local.properties
#          script: |
#              echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
        - name: Get Flutter packages
          script: |
            cd ./codemagic_app &&
            flutter packages pub get
        - name: Build APK with Flutter
          script: |
            cd ./codemagic_app &&
            flutter build apk --release
        artifacts:
            - codemagic_app/build/**/outputs/**/*.apk
            - codemagic_app/build/**/outputs/**/mapping.txt
            - codemagic_app/flutter_drive.log
        publishing:
          email:
            recipients:
              - roel@rtiblockchain.nl
            notify:
              success: true
              failure: false